### ISSUE TITLE
Currency extraction from url coming empty

### ISSUE THREAD

**Issue by imbf98** [io238/laravel-iso-countries#1]
Hi, 

Im trying to use this lib but i am getting the problem that currency seeds are coming empty because load currency JSON url is giving status 404.

// Load Currency JSON
Http::get('[https://gist.githubusercontent.com/Fluidbyte/2973986/raw/8bb35718d0c90fdacb388961c98b8d56abc392c9/Common-Currency.json'](https://gist.githubusercontent.com/Fluidbyte/2973986/raw/8bb35718d0c90fdacb388961c98b8d56abc392c9/Common-Currency.json%27));

Can you give me a solution for this? 

Thanks

**Comment by io238** [comment]
Indeed, some of the external resources are not available anymore. I've been working on several changes to this package, including a fix for this missing data source. I'll publish a new release very soon and will keep you posted here as well.

**Comment by io238** [comment]
This has been fixed by loading all dependencies into version control instead of relying on online resources.
