### ISSUE TITLE
Facade issue

### ISSUE THREAD

**Issue by imanimanyara** [io238/laravel-iso-countries#2]
Facing an issue when running the following command on laravel 9;

php artisan ide-helper:generate --ansi
Exception: Target class [iso-countries] does not exist.
Skipping \Io238\ISOCountries\ISOCountriesFacade.

In Facade.php line 216:
                                         
  Illegal offset type in isset or empty

**Comment by io238** [comment]
Thanks for reporting this. It will be resolved in the next release.

**Comment by Esirei** [comment]
@io238 any update on the next release?

**Comment by io238** [comment]
This package is not using the facade anymore.
